### ISSUE TITLE
Pack has no license

### ISSUE THREAD

**Issue by patrickwhite256** [SapphireSapphic/TunicTracker#24]
title. Since the pack has no license we're actually in kind of a grey area when it comes to modifying/contributing to this repo and honestly even using the pack.

More info: https://choosealicense.com/no-permission/

It'd be great if we could get a license ([MIT](https://choosealicense.com/licenses/mit/) is my preference but of course up to you) added so we can use the pack & contribute without any legal quandaries.

**Comment by ScipioWright** [comment]
Agreed, we should add an MIT license to the repo. I'll go poke sapphic.

**Comment by Br00ty** [comment]
done
