### ISSUE TITLE
"initial_active_state": true for abilities, should be false?

### ISSUE THREAD

**Issue by DJChupa13** [SapphireSapphic/TunicTracker#6]
Hey!  I am trying out the AP build of the TUNIC randomizer and was interested in this tracker pack since it had auto-tracking.

I noticed that the three manual-based abilities - pray, cross, and ice rod - are on by default.  It looks like their initial active state property is set to true.  However, this should only be set to true _if ability_shuffling is false_.

I almost feel as if the tracker settings panel (where you can set glitched vs. glitchless and the goal) should include ability shuffling as an option.  Auto-tracking should then set that option automatically for the user (and maybe even lock its setting until auto-tracking is turned off).

**Comment by Br00ty** [comment]
this is old and has been fixed
